import { AuctionStatus } from "@prisma/client";
import { addHours, subHours } from "date-fns";

export type SeedPropertyRow = {
  title: string;
  description: string;
  propertyType: string;
  location: string;
  city: string;
  area: number;
  bedrooms: number | null;
  bathrooms: number | null;
  amenities: string[];
  startingPrice: number;
  currentPrice: number;
  minimumIncrement: number;
  auctionStart: Date;
  auctionEnd: Date;
  status: AuctionStatus;
  latitude: number;
  longitude: number;
};

const now = new Date();

/** Distinct Unsplash sources so cards look varied in the grid */
export const seedImageTemplates = [
  "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1486406146926-c627a92ad4ab?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
];

export function seedProperties(): SeedPropertyRow[] {
  return [
    {
      title: "Palm Jumeirah Waterfront Villa",
      description: "Contemporary six-bedroom villa with private beach access and panoramic Gulf views.",
      propertyType: "VILLA",
      location: "Palm Jumeirah, Dubai",
      city: "Dubai",
      area: 7820,
      bedrooms: 6,
      bathrooms: 7,
      amenities: ["Private Beach", "Infinity Pool", "Smart Home", "Covered Parking"],
      startingPrice: 12_500_000,
      currentPrice: 14_450_000,
      minimumIncrement: 50_000,
      auctionStart: subHours(now, 10),
      auctionEnd: addHours(now, 30),
      status: AuctionStatus.ACTIVE,
      latitude: 25.1124,
      longitude: 55.139,
    },
    {
      title: "Downtown Skyline Apartment",
      description: "Three-bedroom apartment in Downtown with Burj Khalifa views and concierge access.",
      propertyType: "APARTMENT",
      location: "Downtown Dubai, Dubai",
      city: "Dubai",
      area: 2180,
      bedrooms: 3,
      bathrooms: 4,
      amenities: ["Gym", "Pool", "Concierge", "Balcony"],
      startingPrice: 3_200_000,
      currentPrice: 3_925_000,
      minimumIncrement: 25_000,
      auctionStart: subHours(now, 7),
      auctionEnd: addHours(now, 18),
      status: AuctionStatus.ACTIVE,
      latitude: 25.1972,
      longitude: 55.2744,
    },
    {
      title: "Sharjah Corporate Office Floor",
      description: "Full office floor with private reception and meeting suites in a grade-A tower.",
      propertyType: "COMMERCIAL",
      location: "Al Majaz 2, Sharjah",
      city: "Sharjah",
      area: 7613,
      bedrooms: null,
      bathrooms: 4,
      amenities: ["Meeting Rooms", "Reception", "Pantry", "Parking"],
      startingPrice: 3_100_000,
      currentPrice: 3_670_000,
      minimumIncrement: 10_000,
      auctionStart: subHours(now, 4),
      auctionEnd: addHours(now, 20),
      status: AuctionStatus.ACTIVE,
      latitude: 25.3374,
      longitude: 55.3773,
    },
    {
      title: "Aljada Family Townhouse",
      description: "Four-bedroom townhouse with landscaped courtyard and direct access to schools and retail.",
      propertyType: "TOWNHOUSE",
      location: "Aljada, Sharjah",
      city: "Sharjah",
      area: 2940,
      bedrooms: 4,
      bathrooms: 5,
      amenities: ["Courtyard", "Maid Room", "Community Park", "Garage"],
      startingPrice: 1_450_000,
      currentPrice: 1_720_000,
      minimumIncrement: 10_000,
      auctionStart: subHours(now, 2),
      auctionEnd: addHours(now, 48),
      status: AuctionStatus.ACTIVE,
      latitude: 25.3073,
      longitude: 55.4707,
    },
    {
      title: "Yas Island Marina Plot",
      description: "Corner waterfront land parcel with marina access — rare freehold opportunity.",
      propertyType: "LAND",
      location: "Yas Island, Abu Dhabi",
      city: "Abu Dhabi",
      area: 14_200,
      bedrooms: null,
      bathrooms: null,
      amenities: ["Marina Access", "Corner Plot", "Utilities Nearby"],
      startingPrice: 8_900_000,
      currentPrice: 10_150_000,
      minimumIncrement: 50_000,
      auctionStart: subHours(now, 12),
      auctionEnd: addHours(now, 60),
      status: AuctionStatus.ACTIVE,
      latitude: 24.4672,
      longitude: 54.603,
    },
    {
      title: "Business Bay Canal Loft",
      description: "Two-level loft with double-height glazing, canal views, and hotel amenities.",
      propertyType: "APARTMENT",
      location: "Business Bay, Dubai",
      city: "Dubai",
      area: 1890,
      bedrooms: 2,
      bathrooms: 3,
      amenities: ["Canal View", "Gym", "Co-working", "Valet"],
      startingPrice: 1_980_000,
      currentPrice: 2_305_000,
      minimumIncrement: 15_000,
      auctionStart: subHours(now, 6),
      auctionEnd: addHours(now, 14),
      status: AuctionStatus.ACTIVE,
      latitude: 25.185,
      longitude: 55.2644,
    },
    {
      title: "DIP Logistics Warehouse",
      description: "High-bay warehouse with loading docks, sprinkler system, and 24/7 security.",
      propertyType: "COMMERCIAL",
      location: "Dubai Investment Park, Dubai",
      city: "Dubai",
      area: 45_000,
      bedrooms: null,
      bathrooms: 6,
      amenities: ["Loading Bays", "Sprinklers", "Security", "Three-phase Power"],
      startingPrice: 5_400_000,
      currentPrice: 6_180_000,
      minimumIncrement: 30_000,
      auctionStart: subHours(now, 8),
      auctionEnd: addHours(now, 72),
      status: AuctionStatus.ACTIVE,
      latitude: 24.9789,
      longitude: 55.1644,
    },
    {
      title: "Saadiyat Beach Estate Villa",
      description: "Mediterranean-style five-bed villa steps from Saadiyat Beach Club and cultural district.",
      propertyType: "VILLA",
      location: "Saadiyat Island, Abu Dhabi",
      city: "Abu Dhabi",
      area: 6120,
      bedrooms: 5,
      bathrooms: 6,
      amenities: ["Beach Club", "Pool", "Driver Room", "Solar Ready"],
      startingPrice: 9_750_000,
      currentPrice: 11_100_000,
      minimumIncrement: 75_000,
      auctionStart: subHours(now, 14),
      auctionEnd: addHours(now, 54),
      status: AuctionStatus.ACTIVE,
      latitude: 24.5371,
      longitude: 54.4139,
    },
    {
      title: "Al Hamra Marina Residence",
      description: "Sea-facing two-bedroom with yacht marina, golf course, and resort pools.",
      propertyType: "APARTMENT",
      location: "Al Hamra Village, Ras Al Khaimah",
      city: "Ras Al Khaimah",
      area: 1420,
      bedrooms: 2,
      bathrooms: 2,
      amenities: ["Marina", "Golf", "Pools", "Beach Access"],
      startingPrice: 890_000,
      currentPrice: 1_055_000,
      minimumIncrement: 5000,
      auctionStart: subHours(now, 3),
      auctionEnd: addHours(now, 26),
      status: AuctionStatus.ACTIVE,
      latitude: 25.6915,
      longitude: 55.7608,
    },
    {
      title: "Ajman Corniche Retail Block",
      description: "Ground plus mezzanine retail facing corniche — strong foot traffic and parking.",
      propertyType: "COMMERCIAL",
      location: "Ajman Corniche Road, Ajman",
      city: "Ajman",
      area: 5200,
      bedrooms: null,
      bathrooms: 4,
      amenities: ["Street Frontage", "Mezzanine", "Parking", "Signage Rights"],
      startingPrice: 2_650_000,
      currentPrice: 3_010_000,
      minimumIncrement: 20_000,
      auctionStart: subHours(now, 5),
      auctionEnd: addHours(now, 40),
      status: AuctionStatus.ACTIVE,
      latitude: 25.4052,
      longitude: 55.4406,
    },
  ];
}
